server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/ctf5g;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:independent-study}
      secret: ${JWT_SECRET:change-me-in-env-please-change-me-32bytes-min}
      expirationMinutes: ${JWT_EXP_MINUTES:60}

